---
- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory

- name: Remove default html directory
  file:
    path: "{{ www_root }}/html"
    state: absent

- name: Create site directories
  file:
    path: "{{ www_root }}/{{ item.key }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  loop: "{{ sites | dict2items }}"

- name: Create logs directories
  file:
    path: "{{ www_root }}/{{ item.key }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  loop: "{{ sites | dict2items }}"
