---
- name: Search for custom vhost config files
  stat:
    path: "{{ item.value.vhost | default('files/vhosts/' + item.key + '.conf.j2') }}"
  register: sites_custom_vhost
  delegate_to: localhost
  become: false
  when: item.value.enabled | default(true)
  loop: "{{ sites | dict2items }}"
  tags: [vhosts]

- name: Choose vhost config file to use
  set_fact:
    sites_vhosts: "{{ sites_vhosts | default({}) | combine({ item.item.key: item.stat.exists | ternary(item.item.value.vhost | default('files/vhosts/' + item.item.key + '.conf.j2'), 'vhost.conf.j2') }) }}"
  loop: "{{ sites_custom_vhost.results }}"
  tags: [vhosts]

- name: Add managed vhost config files.
  template:
    src: "{{ sites_vhosts[item.key] }}"
    dest: "{{ nginx_path }}/sites-available/{{ item.key }}.conf"
    force: true
    owner: root
    group: root
    mode: 0644
  when: item.value.enabled | default(true)
  loop: "{{ sites | dict2items }}"
  notify: Reload nginx
  tags: [vhosts]

- name: Activate enabled sites vhost.
  file:
    src: "{{ nginx_path }}/sites-available/{{ item.key }}.conf"
    dest: "{{ nginx_path }}/sites-enabled/{{ item.key }}.conf"
    owner: root
    group: root
    state: link
  when: item.value.enabled | default(true)
  loop: "{{ sites | dict2items }}"
  notify: Reload nginx
  tags: [vhosts]

- name: Deactivate disabled sites vhost.
  file:
    path: "{{ nginx_path }}/sites-enabled/{{ item.key }}.conf"
    state: absent
  when: not item.value.enabled | default(true)
  loop: "{{ sites | dict2items }}"
  notify: Reload nginx
  tags: [vhosts]
