---
- name: Initialize the deploy root and gather facts
  deploy_helper:
    path: "{{ deploy_site_root }}"

- name: Add known hosts
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.key | default(omit) }}"
    path: "{{ item.path | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ known_hosts | default([]) | flatten(levels=1) }}"

- name: Clone the project to the new release folder
  git:
    repo: "{{ deploy_site_repository }}"
    dest: "{{ deploy_helper.new_release_path }}"
    version: "{{ deploy_site_branch }}"

- name: Add an unfinished file, to allow cleanup on successful finalize
  file:
    path: "{{ deploy_helper.new_release_path }}/{{ deploy_helper.unfinished_filename }}"
    state: touch

- name: Search for a deploy_build tasks file
  stat:
    path: "{{ deploy_site_build_tasks }}"
  delegate_to: localhost
  become: false
  register: deploy_build_tasks_file
  become: no
  tags: [build]

- name: Include deploy_build tasks
  include: "{{ deploy_site_build_tasks }}"
  when: deploy_build_tasks_file.stat.exists
  tags: [build]

- name: Create shared folders
  file:
    path: "{{ deploy_helper.shared_path }}/{{ item.src }}"
    mode: "{{ item.mode | default(775) }}"
    state: directory
  loop: "{{ deploy_site_shared | flatten(levels=1) }}"

- name: Add symlinks from the new release to the shared folders
  file:
    path: "{{ deploy_helper.new_release_path }}/{{ item.path }}"
    src: "{{ deploy_helper.shared_path }}/{{ item.src }}"
    state: link
  loop: "{{ deploy_site_shared | flatten(levels=1) }}"

- name: Finalize the deploy, removing the unfinished file and switching the symlink
  deploy_helper:
    path: "{{ deploy_site_root }}"
    release: "{{ deploy_helper.new_release }}"
    state: finalize
    keep_releases: "{{ deploy_site_keep_releases }}"

- name: Search for a deploy_finalize tasks file
  stat:
    path: "{{ deploy_site_finalize_tasks }}"
  delegate_to: localhost
  become: false
  register: deploy_finalize_tasks_file
  become: no
  tags: [finalize]

- name: Include deploy_finalize tasks
  include: "{{ deploy_site_finalize_tasks }}"
  when: deploy_finalize_tasks_file.stat.exists
  tags: [finalize]
