---
roles:
  - name: composer
    version: 1.9.0
    src: geerlingguy.composer

  - name: git
    version: 3.0.0
    src: geerlingguy.git

  - name: nginx
    version: 2.8.0
    src: geerlingguy.nginx

  - name: php-versions
    version: 4.0.4
    src: geerlingguy.php-versions

  - name: php
    version: 4.5.1
    src: geerlingguy.php

  - name: rvm
    version: v2.1.2
    src: rvm.ruby

  - name: postgresql
    version: 3.0.0
    src: geerlingguy.postgresql

  - name: npm
    version: 2.4.1
    src: robertdebock.npm
