---
- name: Test Connection and determine remote user
  hosts: zsx-srv2
  gather_facts: false
  roles:
    - { role: connection,   tags: [connection, always] }

- name: Provisioning
  hosts: zsx-srv2
  become: yes
  roles:
    - { role: common,       tags: [common] }
    - { role: users,        tags: [users] }
    - { role: git,          tags: [git] }
    - { role: php-versions, tags: [php] }
    - { role: php,          tags: [php] }
    - { role: composer,     tags: [composer] }
    - { role: nginx,        tags: [nginx] }
    - { role: rvm,          tags: [rvm, ruby] }
    - { role: letsencrypt,  tags: [letsencrypt] }
    - { role: sites,        tags: [sites] }
