---
- hosts: zsx-srv2
  become: yes
  roles:
    - { role: git,         tags: [git] }
    - { role: php,         tags: [php] }
    - { role: composer,    tags: [composer] }
    - { role: nginx,       tags: [nginx] }
    - { role: docker,      tags: [docker] }
