---
# ACME
acme_tiny_repo: 'https://github.com/diafygi/acme-tiny.git'
acme_tiny_commit: 'cb094cf3efa34acef8c7139c8480e2135422e755'
acme_tiny_software_directory: /usr/local/letsencrypt
acme_tiny_data_directory: /var/lib/letsencrypt
acme_tiny_challenges_directory: "{{ www_root }}/letsencrypt"

# Let's Encrypt
letsencrypt_ca: 'https://acme-v02.api.letsencrypt.org'
letsencrypt_account_key: '{{ acme_tiny_data_directory }}/account.key'
letsencrypt_keys_dir: "{{ nginx_ssl_path }}/letsencrypt"
letsencrypt_certs_dir: "{{ nginx_ssl_path }}/letsencrypt"
letsencrypt_min_renewal_age: 60
letsencrypt_cronjob_daysofmonth: 1,11,21

# Helpers
sites_using_letsencrypt: "[{% for name, site in sites.items() | list if site.ssl | default(false) %}'{{ name }}',{% endfor %}]"
missing_hosts: "{{ site_hosts | difference((current_hosts.results | selectattr('item.key', 'equalto', item.key) | selectattr('stdout_lines', 'defined') | sum(attribute='stdout_lines', start=[]) | map('trim') | list | join(' ')).split(' ')) }}"
letsencrypt_cert_ids: "{ {% for item in (generate_cert_ids | default({'results':[{'skipped':True}]})).results if item is not skipped %}'{{ item.item.key }}':'{{ item.stdout }}', {% endfor %} }"
