---
# Helpers
site_root: "{{ item.value.root | default(www_root + '/' + item.key) }}"
site_ssl_enabled: "{{ item.value.ssl | default(false) }}"
site_hosts: "{{ ([item.value.hosts.canonical] + (item.value.hosts.redirects | default([]))) }}"
