---
# Ansible
vault_ansible_sudo_pass: "{{ ansible_sudo_pass }}"
ansible_ssh_host: "{{ vault_ansible_ssh_host }}"
ansible_ssh_private_key_file: ~/.ssh/id_rsa

# Composer
composer_keep_updated: false
composer_global_packages: []

# PHP
php_default_version_ubuntu: 7.4
php_packages_extra: []
