---
# Ansible
vault_ansible_sudo_pass: "{{ ansible_sudo_pass }}"
ansible_ssh_host: "{{ vault_ansible_ssh_host }}"
ansible_ssh_private_key_file: ~/.ssh/id_rsa

# Time
ntp_timezone: Europe/Paris

# Locales
locales:
 - en_US.UTF-8
 - fr_FR.UTF-8

# Python
ansible_python_interpreter: /usr/bin/python3

# APT
apt_keys: {}
apt_repositories:
  - ppa:deadsnakes/ppa
apt_packages:
  software-properties-common: present
  build-essential: present
  curl: present
  nano: present
  python: present
  unzip: present
  cron: present
  python3.7: present
  python3.7-venv: present
  python3-pip: present
  gettext: present
apt_cache_valid_time: 3600

# Composer
composer_keep_updated: false
composer_global_packages: []

# PHP
php_version: 7.4
php_versions_install_recommends: false
php_webserver_daemon: 'nginx'
php_packages_extra: []

# Nginx
www_root: /var/www
nginx_path: /etc/nginx
nginx_ssl_path: "{{ nginx_path }}/ssl"

# Ruby
rvm1_rubies:
  - ruby-2.4.0
rvm1_bundler_install: True
rvm1_install_path: /usr/local/rvm
rvm1_install_flags: '--auto-dotfiles'
rvm1_user: root
rvm1_rvm_version: stable
rvm1_rvm_check_for_updates: False

# PostgreSQL
postgresql_locales: "{{ locales }}"
postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: md5}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}

# Node.js
nodejs_version: "12.x"

# Known hosts
known_hosts:
  - name: github.com
    key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
