---
# Ansible
vault_ansible_sudo_pass: "{{ ansible_sudo_pass }}"
ansible_ssh_host: "{{ vault_ansible_ssh_host }}"
ansible_ssh_private_key_file: ~/.ssh/id_rsa

# Time
ntp_timezone: Europe/Paris

# APT
apt_keys: []
apt_packages:
  build-essential: present
  curl: present
  nano: present
  python: present
  unzip: present
apt_cache_valid_time: 3600

# Composer
composer_keep_updated: false
composer_global_packages: []

# PHP
php_default_version_ubuntu: 7.4
php_packages_extra: []

# Nginx
www_root: /var/www
nginx_path: /etc/nginx

# Known hosts
known_hosts:
  - name: github.com
    key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
