---
# Sites
sites:
  listenmu.com:
    hosts:
      canonical: listenmu.com
      redirects:
        - www.listenmu.com
    ssl: false
    repository: git@github.com:zessx/listenmu.com.git
    branch: main
    vhost: files/vhosts/listenmu.com.conf.j2
