---
# Sites
sites:

  listenmu.com:
    hosts:
      canonical: listenmu.com
      redirects:
        - www.listenmu.com
    ssl: true
    repository: git@github.com:zessx/listenmu.com.git
    branch: main
    vhost: files/vhosts/listenmu.com.conf.j2

  doc.smarchal.com:
    hosts:
      canonical: doc.smarchal.com
    ssl: true
    repository: git@github.com:zessx/doc.smarchal.com.git
    branch: main
    vhost: files/vhosts/doc.smarchal.com.conf.j2
    index: index.php
    shared:
      - path: app/cache
        src: cache
      - path: private
        src: private
      - path: public
        src: public

  archive.smarchal.com:
    hosts:
      canonical: archive.smarchal.com
    ssl: true
    repository: git@github.com:zessx/archive.smarchal.com.git
    branch: main
    vhost: files/vhosts/archive.smarchal.com.conf.j2
    index: "index.php index.html"

  pwd.smarchal.com:
    hosts:
      canonical: pwd.smarchal.com
    ssl: true
    repository: git@github.com:zessx/nikagi.git
    branch: master
    vhost: files/vhosts/pwd.smarchal.com.conf.j2
    index: index.php
    shared:
      - path: config
        src: config

  blog.smarchal.com:
    hosts:
      canonical: blog.smarchal.com
    ssl: true
    repository: git@github.com:zessx/blog.git
    branch: master
    vhost: files/vhosts/blog.smarchal.com.conf.j2
    web_root: /_site
