---
# Unix users
admin_user: admin
web_user: web
web_group: www-data

# Nginx
nginx_user: "{{ web_user }} {{ web_group }}"

# Unix users
users:
  - name: "{{ admin_user }}"
    groups:
      - "{{ web_group }}"
      - sudo
    keys:
      - "https://github.com/zessx.keys"
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
      - "https://github.com/zessx.keys"

# Git
git_user: zessx

# Sudo services for web user
web_sudo_services:
  - "/usr/sbin/service php{{ php_version }}-fpm *"
