---
- name: Ensure requested groups are present
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ users | sum(attribute='groups', start=[]) | list | unique | flatten(levels=1) }}"

- name: Ensure sudo group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Setup users
  user:
    name: "{{ item.name }}"
    group: "{{ item.groups[0] }}"
    groups: "{{ item.groups | join(',') }}"
    password: '{% for user in vault_users | default([]) if user.name == item.name and user.password is defined %}{{ user.password | password_hash("sha512", (user.salt | default(""))[:16] | regex_replace("[^\.\/a-zA-Z0-9]", "x")) }}{% else %}{{ None }}{% endfor %}'
    state: present
    shell: /bin/bash
    update_password: "{{ item.update_password | default('always') }}"
  loop: "{{ users | flatten(levels=1) }}"

- name: Add SSH keys
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  loop: "{{ users | default([]) | subelements('keys') }}"

- name: Setup server private SSH key
  copy:
    src: files/ssh/server.key
    dest: "/home/{{ admin_user }}/.ssh/id_rsa"
    owner: "{{ admin_user }}"
    mode: 0600

- name: Setup server public SSH key
  copy:
    src: files/ssh/server.key.pub
    dest: "/home/{{ admin_user }}/.ssh/id_rsa.pub"
    owner: "{{ admin_user }}"
    mode: 0644
