---
- name: Ensure SSHPass is installed
  become: false
  homebrew:
    name: esolitos/ipa/sshpass
    state: present
  delegate_to: localhost
  tags: [sshpass]

- name: Add APT repositories
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
  loop: "{{ apt_repositories | default([]) }}"

- name: Add APT keys
  apt_key:
    keyserver: "{{ item.value.keyserver }}"
    id: "{{ item.value.id }}"
  loop: "{{ apt_keys | dict2items }}"

- name: Update apt packages
  apt:
    update_cache: yes

- name: Checking essentials
  apt:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"
  loop: "{{ apt_packages | dict2items }}"

- name: Validate timezone variable
  stat:
    path: /usr/share/zoneinfo/{{ ntp_timezone }}
  register: timezone_path
  changed_when: false

- name: Explain timezone error
  fail:
    msg: "{{ ntp_timezone }} is not a valid timezone. For a list of valid timezones, check https://php.net/manual/en/timezones.php"
  when: not timezone_path.stat.exists

- name: Add myhostname to nsswitch.conf to ensure resolvable hostname
  lineinfile:
    backrefs: yes
    backup: yes
    dest: /etc/nsswitch.conf
    line: \1 myhostname
    regexp: ^(hosts\:((?!myhostname).)*)$
    state: present

- name: Retrieve SSH client IP
  block:
    - ipify_facts:
      delegate_to: localhost
      become: no
      when: ssh_client_ip_lookup | default(true)
  rescue:
    - fail:
        msg: "External IP resolution failed. Check that your DNS servers are working. Try to disable DNSCrypt if you are using it."

- name: Generate required locales
  locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ locales | default([]) | flatten(levels=1) }}"
  tags: [locales]
