---
- name: Create directories and set permissions
  file:
    mode: "{{ item.mode | default(omit) }}"
    path: "{{ item.path }}"
    state: directory
  with_items:
    - path: "{{ acme_tiny_data_directory }}"
      mode: '0700'
    - path: "{{ acme_tiny_data_directory }}/csrs"
    - path: "{{ acme_tiny_software_directory }}"
    - path: "{{ acme_tiny_challenges_directory }}"
    - path: "{{ letsencrypt_certs_dir }}"
      mode: '0700'

- name: Clone acme-tiny repository
  git:
    dest: "{{ acme_tiny_software_directory }}"
    repo: "{{ acme_tiny_repo }}"
    version: "{{ acme_tiny_commit }}"
    accept_hostkey: yes

- name: Generate a new account key
  shell: openssl genrsa 4096 > {{ letsencrypt_account_key }}
  args:
    creates: "{{ letsencrypt_account_key }}"
