---
default_git_branch: HEAD
default_keep_releases: 3

# Helpers
deploy_site_root: "{{ sites[site].root | default(www_root + '/' + site) }}"
deploy_site_shared: "{{ sites[site].shared | default([]) }}"
deploy_site_keep_releases: "{{ sites[site].keep_releases | default(default_keep_releases) }}"
deploy_site_repository: "{{ sites[site].repository }}"
deploy_site_branch: "{{ sites[site].branch | default(default_git_branch) }}"
deploy_site_env: "{{ sites[site].env | default({}) }}"
deploy_site_build_tasks: "{{ sites[site].build_tasks | default('files/deploy/build/' + site + '.yml') }}"
deploy_site_finalize_tasks: "{{ sites[site].finalize_tasks | default('files/deploy/finalize/' + site + '.yml') }}"
